global using System.Reflection;
global using System.Xml;
global using System.Xml.Linq;
global using CommandLine;
global using NuGet.Configuration;
global using NuGet.Protocol;
global using NuGet.Protocol.Core.Types;
global using NuGet.Versioning;
global using Serilog;